# Generated by Django 3.0.7 on 2021-05-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='students',
            name='case_of_emergency',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='students',
            name='disease',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='students',
            name='etnia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='students',
            name='mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='personal_references9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
