# Generated by Django 3.1.2 on 2021-03-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('clave', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
            },
        ),
    ]
